## pushstate redirect 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "/static/*"
  [headers.values]
	cache-control = '''
	max-age=31536000,
  immutable,
  public
  '''